### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheUltimate455**
i changed the description

### CODE REVIEW

**Review by technocodermlondie — CHANGES_REQUESTED** [review]
Please retain the line I already had and make your additions below it.

**Comment by TheUltimate455** [comment]
Ok, I will.

**Comment by TheUltimate455** [comment]
I made the changes

**Comment by TheUltimate455** [comment]
i have made the changes to the repository

**Comment by technocodermlondie** [comment]
Will merge changes.

**Pull request merged**
